#include <iostream>
using namespace std;

int main() {
    int Taille, pos, N;
    int T[100];

    // إدخال حجم الجدول
    cout << "Entrez la taille du tableau : ";
    cin >> Taille;

    // إدخال عناصر الجدول
    for (int i = 0; i < Taille; i++) {
        cout << "T[" << i + 1 << "] = ";
        cin >> T[i];
    }

    // إدخال القيمة الجديدة
    cout << "Entrez la valeur a inserer : ";
    cin >> N;

    // إدخال البوزيشن
    cout << "Entrez la position : ";
    cin >> pos;

    // التحقق من صحة البوزيشن
    if (pos <= 0 || pos > Taille + 1) {
        cout << "Position invalide !" << endl;
        return 1;
    }

    // الإزاحة من الآخر
    for (int i = Taille; i >= pos; i--) {
        T[i] = T[i - 1];
    }

    // إدخال القيمة
    T[pos - 1] = N;
    Taille++;

    // عرض الجدول النهائي
